apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-argocd-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/repo-status-check-interval: "30s"
    argocd-image-updater.argoproj.io/image-list: app1=aries5533/main-service, app2=aries5533/aux-service 
    argocd-image-updater.argoproj.io/app1.update-strategy: latest
    argocd-image-updater.argoproj.io/app2.update-strategy: latest
    
spec:
  project: default

  source:
    repoURL: https://github.com/ARIES5533/Article-Argocd-demo.git
    targetRevision: HEAD
    path: Kubernetes-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo-ns


  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
