apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-argocd-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/repo-status-check-interval: "30s"
    argocd-image-updater.argoproj.io/image-list: main-service=aries5533/main-service, aux-service=aries5533/aux-service
    argocd-image-updater.argoproj.io/main-service.update-strategy: latest
    argocd-image-updater.argoproj.io/aux-service.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    
spec:
  project: default

  source:
    repoURL: https://github.com/ARIES5533/Article-Argocd-demo.git
    targetRevision: gitops
    path: Kubernetes-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo-ns


  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
