apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-argocd-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/repo-status-check-interval: "30s"
    
spec:
  project: default

  source:
    repoURL: https://github.com/ARIES5533/Article-Argocd-demo.git
    targetRevision: HEAD
    path: Kubernetes-manifest
    kustomize:
      namePrefix: ""

  destination:
    server: https://kubernetes.default.svc
    namespace: ""


  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
