apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-challenge-gitops
  namespace: argocd
  annotations:
    argocd.argoproj.io/repo-status-check-interval: "30s"
    
spec:
  project: default

  source:
    repoURL: https://github.com/ARIES5533/CLOUD-CHALLENGE.git
    targetRevision: HEAD
    path: k8s
    kustomize:
      namePrefix: ""

  destination:
    server: https://kubernetes.default.svc
    namespace: ""

  ignoreDifferences:
    - group: ""
      kind: ServiceAccount
      name: aux-service-sa
      namespace: aux-service-ns


  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
