apiVersion: apps/v1
kind: Deployment
metadata:
  name: aux-deployment
  namespace: aux-service-ns
  labels:
    app: aux-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aux-service
  template:
    metadata:
      labels:
        app: aux-service
    spec:
      serviceAccountName: aux-service-sa
      containers:
      - name: aux-service
        image: aries5533/aux-service:7
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: AUX_SERVICE_VERSION
          value: "1.0.0"
        
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"