apiVersion: v1
kind: Service
metadata:
  name: aux-service
  namespace: aux-service-ns
spec:
  selector:
    app: aux-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP